### Añadimos la nota
POST http://localhost:8080/api/notes/addNota
Content-Type: application/json
X-Username: user1

{
  "title": "Nota de prueba",
  "content": "Contenido de la nota de prueba",
  "privacy": "PUBLIC",
  "latitude": 40.416775,
  "longitude": -3.703790
}

###