###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}


> {%
    client.global.set("access", response.body.access)
%}

### Añadimos la nota
POST http://localhost:8080/notes/addNota
Authorization: Bearer  {{access}}
Content-Type: application/json

{
  "title": "Nota de prueba",
  "type": "LANDSCAPE",
  "content": "Contenido de la nota de prueba",
  "privacy": "PUBLIC",
  "latitude": 40.416775,
  "longitude": -3.703790
}