###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}


> {%
    client.global.set("access", response.body.access)
%}


### notas: eliminar una nota
DELETE http://localhost:8080/notes/2
Authorization: Bearer {{access}}
Accept: application/json

