###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}


> {%
    client.global.set("access", response.body.access)
%}


### notas: ordena la lista ascendente
DELETE http://localhost:8080/notes/1
Authorization: Bearer  {{access}}
Accept: application/json

