### GET request to get notes by type with no content
GET http://localhost:8080/notes/type
    ?type=NON_EXISTENT_TYPE
Content-Type: application/json


### GET request to get notes by type HISTORICAL
GET http://localhost:8080/notes/type
    ?type=CLASSIC
Content-Type: application/json

###