###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}


> {%
    client.global.set("access", response.body.access)
%}

### ubicaciones: las de Madrid (devuelve 5)
GET http://localhost:8080/notes/area?latitude=40.416775&longitude=-3.703790
Authorization: Bearer {{access}}
Accept: application/json

### lo mismo pero con menos radio
GET http://localhost:8080/notes/area?latitude=40.416775&longitude=-3.703790
Authorization: Bearer {{access}}
Accept: application/json

### en Barcelona (1 nota)
GET http://localhost:8080/notes/area?latitude=41.403706&longitude=2.173504
Authorization: Bearer {{access}}
Accept: application/json

### (vacio)
GET http://localhost:8080/notes/area?latitude=42.0&longitude=-4.0
Authorization: Bearer {{access}}
Accept: application/json

### Actualizar nota
PUT http://localhost:8080/notes
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "id": 548,
  "title": "Updated Note Title",
  "content": "This is the updated content of my note.",
  "privacy": "PRIVATE",
  "latitude": 40.7128,
  "longitude": -74.0060
}

### Calificar nota
PATCH http://localhost:8080/notes/550/rate?rating=8
Authorization: Bearer {{access}}
Content-Type: application/json

### Login
POST http://localhost:8080/login
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "username": "bob",
  "password": "juan"
}

> {%
    client.global.set("token", response.body.access);
%}


### Obtener notas
GET https://informatica.iesquevedo.es/nomada/notes
Content-Type: application/json
Authorization: Bearer {{token}}

### A
GET https://informatica.iesquevedo.es/nomada/user/likes
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar usuarios (con token si es necesario)
GET https://informatica.iesquevedo.es/nomada/user/all?text=ali
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener notas por id
GET http://localhost:8080/notes/640
Authorization: Bearer {{access}}
Content-Type: application/json
