###
POST http://localhost:8080/login
Content-Type: application/json

{
  "password": "12345678",
  "email": "hola@gmail.com"
}

> {%
    client.global.set("access", response.body.access)
%}

### notas: ordena la lista ascendente
GET http://localhost:8080/notes/sorted?ascending=true
Authorization: Bearer {{access}}
Accept: application/json

### notas: ordena la lista descendente
GET http://localhost:8080/notes/sorted?ascending=false
Authorization: Bearer {{access}}
Accept: application/json

### savedNotas: da las notas guardadas de un usuario
GET http://localhost:8080/notes/saves
Authorization: Bearer {{access}}
Accept: application/json

### savedNotas: guardar nota
POST http://localhost:8080/social/saves
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access}}

username=hola&noteId=3

### savedNotas: Eliminar una nota de guardados
DELETE http://localhost:8080/notes/saves
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access}}

noteId=409