### notas: ordena la lista ascendente
GET http://localhost:8080/notes/sorted?ascending=true
Accept: application/json

### notas: ordena la lista descendente
GET http://localhost:8080/notes/sorted?ascending=false
Accept: application/json

### savedNotas: da las notas guardadas de un usuario
GET http://localhost:8080/notes/saveds?username=user1
Accept: application/json

### savedNotas: guardar nota
POST http://localhost:8080/social/saveds
Content-Type: application/x-www-form-urlencoded

username=user1&noteId=409

###
DELETE http://localhost:8080/notes/saveds
Content-Type: application/x-www-form-urlencoded

noteId=409