###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "jorge_official",
  "password": "12345678",
  "email": "jorgenovillo2005@gmail.com"
}

###
GET http://localhost:8080/confirm?
    code=60wFPp_iXY2lywAv9Nyy1A==


###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}

> {%
    client.global.set("access", response.body.access)
%}


###
GET http://localhost:8080/refresh
Authorization: Bearer {{access}}