###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}


###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "jorge",
  "password": "1234",
  "email": "jorge@gmail.com"
}



###
GET http://localhost:8080/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwic3ViIjoidXNlcjEiLCJpYXQiOjE3NDgxMTE0NjYsImV4cCI6MTc0ODcxNjI2Nn0.nK8P9wc97_Rjakdj8vKFGXrnbaN8FP2RVewv9XRaOy4